# GitHub-script action https://github.com/actions/github-script
# GitHub context https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: '[Automation] Add PR to project'
on:
  pull_request_target:
  pull_request:
    types: [opened]

jobs:
  create-pr-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add PR to project board
        uses: actions/github-script@v5
        continue-on-error: true
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            github.rest.projects.createCard({
            column_id: 17134543, # IN_PROGRESS column
            content_id: context.payload.pull_request.id,
            content_type: "PullRequest"
            });

      - name: Add PR to project board
        continue-on-error: true
        env:
          USER: "${{ github.actor }}"
          TOKEN: "${{ secrets.ADMIN_PAT }}"
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
            -u ${USER}:${TOKEN} \
          -d '{"content_id": context.payload.pull_request.id, "content_type": "PullRequest", "column_id": 17134543 }' \
            https://api.github.com/projects/columns/17134543/cards
