name: 'Context'
on:
  pull_request_target

jobs:
  view-context:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        continue-on-error: true
        uses: actions/github-script@v5
        with:
          script: console.log(context)
      - name: Check secret
        continue-on-error: true
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
          USER: ${{ github.actor }}
        run: |
          echo "Secret: $SUPER_SECRET"
          echo "${USER}"
